[package]
name = "fileSystemAnalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
sha2 = "0.10.8"
glob = "0.3.1"
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4.39"